config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "toppages#index"
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get "signup", to: "users#new"
  resources :users, only: [:index, :show, :new, :create, :edit, :update] do
    member do
      get :followings
      get :followers
      get :likes
    end
    collection do
      get :search
    end
  end
  
  resources :articles do
    collection do
      get :search
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
  
  get '/articles/hashtag/:hashtag_id', to: "articles#hashtag"
  get "/articles/category/:category_id", to: "articles#category"
  
  resources :hashtags, only: [:index]
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :favorites, dependent: :destroy
  has_many :users, through: :favorites
  has_many :tagmanagements, dependent: :destroy
  has_many :hashtags, through: :tagmanagements, source: :hashtag
  
  validates :title, presence: true, length: { maximum: 20 }
  validates :content, presence: true, length: { maximum: 2000 }

  #記事(article)保存後に処理
  after_create do
    article = Article.find_by(id: self.id)
    #保存した記事のcontentの中から#の後に続くハッシュタグをスキャンして配列に入れる]
    hashtags  = self.content.scan(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/)
    hashtags.uniq.map do |hashtag|
      #ハッシュタグを'#'を外して保存
      tag = Hashtag.find_or_create_by(hashname: hashtag.downcase.delete('#'))
      #中間テーブルに記事のidとハッシュタグのidを保存
      Tagmanagement.find_or_create_by(article_id: article.id,hashtag_id: tag.id)
    end
  end
  
  #記事更新前のデータを代入
  before_update do
    @before_article = Article.find_by(id: self.id)
  end

  after_update do
    article = Article.find_by(id: self.id)
    #記事idを持った中間テーブルカラムを全件削除する
    Tagmanagement.where(article_id: article.id).destroy_all
    hashtags = self.content.scan(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/)
    hashtags.uniq.map do |hashtag|
      tag = Hashtag.find_or_create_by(hashname: hashtag.downcase.delete('#'))
      Tagmanagement.find_or_create_by(article_id: article.id,hashtag_id: tag.id)
    end
    #更新前の記事のcontentの中から#の後に続くハッシュタグをスキャンして配列に入れる
    hashtags  = @before_article.content.scan(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/)
    hashtags.uniq.map do |hashtag|
      tag = Hashtag.find_by(hashname: hashtag.downcase.delete('#'))
      #ハッシュタグが持つ記事が無ければそのハッシュタグを削除
      if tag.articles.blank?
        tag.destroy
      end
    end
  end
  
  after_destroy do
    hashtags  = self.content.scan(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/)
    hashtags.uniq.map do |hashtag|
      tag = Hashtag.find_by(hashname: hashtag.downcase.delete('#'))
      if tag.articles.blank?
        tag.destroy
      end
    end
  end
  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :set_article, only: [:index, :new]
  before_action :article_find, only: [:show, :edit, :update]
  before_action :set_user, only: [:show, :destroy]
  
  def index
      @articles = Article.order(id: :desc).page(params[:page]).per(4)
  end

  def show
  end

  def new
  end

  def create
    @article = current_user.articles.build(article_params)
    if @article.save
      flash[:success] = '記事を投稿しました。'
      redirect_to @article
    else
      flash.now[:danger] = '記事の投稿に失敗しました。'
      render :new
    end
  end

  def edit
  end

  def update
    if @article.update(article_params)
      flash[:success] = '記事を更新しました。'
      redirect_to @article
    else
      @articles = current_user.articles.order(id: :desc).page(params[:page])
      flash.now[:danger] = '記事の更新に失敗しました。'
      render :edit
    end
  end

  def destroy
    @article.destroy
    flash[:success] = '記事を削除しました。'
    redirect_to @user
  end
  
  def hashtag
    @hashtag = Hashtag.find_by(hashname: params[:hashname])
    @articles = @hashtag.articles.page(params[:page]).per(4)
  end
  
  # def search
  #   @search_word = params[:search]
  #   @search_category = params[:category]
    
  #   if @search_category.blank?
  #     @articles = Article.where("(title like ?) OR (content like ?)", "%#{@search_word}%", "%#{@search_word}%").page(params[:page]).per(4)
  #     @articles_count = Article.where("(title like ?) OR (content like ?)", "%#{@search_word}%", "%#{@search_word}%").count
  #   else
  #     @articles = Article.where("(title like ?) OR (content like ?)", "%#{@search_word}%", "%#{@search_word}%").where(category: @search_category).page(params[:page]).per(4)
  #     @articles_count = Article.where("(title like ?) OR (content like ?)", "%#{@search_word}%", "%#{@search_word}%").where(category: @search_category).count
  #   end
    
  #   if @search_word.blank?
  #     @search_word = "指定なし" 
  #   end
  #   if @search_category.blank? 
  #     @search_category = "指定なし" 
  #   end 
  # end
  def search
    @search_word = params[:search]
    
    if params[:category_id].blank?
      @articles = Article.where("(title like ?) OR (content like ?)", "%#{@search_word}%", "%#{@search_word}%").page(params[:page]).per(4)
      @articles_count = Article.where("(title like ?) OR (content like ?)", "%#{@search_word}%", "%#{@search_word}%").count
    else
      @category = Category.find(params[:category_id])
      @articles = Article.where("(title like ?) OR (content like ?)", "%#{@search_word}%", "%#{@search_word}%").where(category_id: @category.id).page(params[:page]).per(4)
      @articles_count = Article.where("(title like ?) OR (content like ?)", "%#{@search_word}%", "%#{@search_word}%").where(category_id: @category.id).count
    end
    
    if @search_word.blank?
      @search_word = "指定なし" 
    end
  end
  
  def category
    @category = Category.find(params[:category_id])
    @articles = @category.articles.page(params[:page]).per(4)
  end
  
  private
  
  def set_article
    @article = current_user.articles.build
  end
  
  def set_user
    @user = @article.user
  end
  
  def article_find
    @article = Article.find_by(id: params[:id])
  end

  def article_params
    params.require(:article).permit(:title,:content,:category_id)
  end
  
  def correct_user
    @article = current_user.articles.find_by(id: params[:id])
    unless @article
      redirect_to root_url
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
  # def render_with_hashtags(hashtag)
    # hashtag.gsub(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/){|word| link_to word, "/articles/hashtag/#{word.delete("#")}"}.html_safe
  # end
  
  def render_with_hashtags(content)
    new_content = content
    hashtags = content.scan(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/)
    hashtags.each do |h|
      hashtag = Hashtag.find_by(hashname: h.delete("#"))
      change_content = new_content.gsub(h){link_to h, "/articles/hashtag/#{hashtag.id}"}.html_safe
      new_content = change_content
    end
    return new_content
  end
end

app/views/articles/_articles.html.erb
<div class="row justify-content-between mb-2">
  <% articles.each do |article| %>
  <div class="d-block d-sm-none col-1"></div>
  <div class="border rounded border-dark mt-3 col-sm-5 col-10">
    <div class="d-flex flex-row justify-content-between">
      <div>
        <p><%= article.title %></p>
      </div>
      <div>
        <%#ユーザー画像設定用%>
        <%# if article.user.image.blank? %>
          <img src="/assets/no_image.png" class='hidden rounded rounded-circle border' width="30" height="30" />
        <%# else %>
          <%#= image_tag article.user.image.to_s, :size => '30', class: "rounded rounded-circle" if article.user.image? %>
        <%# end %>
        <%= link_to article.user.name, user_path(article.user) %>
      </div>
    </div>
    <div>
      <p><%= truncate(article.content, length:30) %></p>
    </div>
    <div class="text-right">
      <%= link_to "続きを読む", article %>
    </div>
  </div>
  <div class="d-block d-sm-none col-1"></div>
  <% end %>
</div>
<%= paginate articles%>

app/views/articles/_search_form.html.erb
<%= form_with(url: search_articles_path, local: true, method: :get) do |f| %>
  <%= content_tag :div, class: "form-group row justify-content-center" do %>
    <%#= f.text_field :search, placeholder: "検索ワードを入力", size: "30",maxlength: "20", class: "col-form-label mr-2" %>
    <%= text_field_tag :search,@search_word, placeholder: "検索ワードを入力", size: "30",maxlength: "20", class: "col-form-label mr-2" %>
    <!--<%= f.select :category, helper_category_search, include_blank: "カテゴリーを指定しない", class: "form-control" %>-->
    <%= f.collection_select :category_id, Category.all, :id, :name, include_blank: "選択して下さい" %>
    <%= f.submit '記事を検索', class: 'btn btn-dark ml-2' %>
  <% end %>
<% end %>

app/views/articles/category.html.erb
<div class="text-center">
  <div><h1>カテゴリー：<%= @category.name %></h1></div>
  <div><h1>記事一覧</h1></div>
</div>
<%= render "articles", articles: @articles %>

app/views/articles/edit.html.erb
<div class="text-center">
  <h1 class="mt-2">記事編集フォーム</h1>
</div>
<div class="container">
<%= form_with(model: @article, local: true) do |f| %>
  <%= render 'layouts/error_messages', model: f.object %>
  
  <div class="form-group row">
    <div class="col-sm-5 text-center col-form-label">
    <%= f.label :title,'タイトル:' %>
    </div>
    <%= f.text_field :title, class: 'form-control col-sm-7'%>
  </div>

  <div class="form-group row">
    <div class="col-sm-5 text-center col-form-label">
    <%= f.label :content, '内容:' %>
    </div>
    <%= f.text_area :content, class: 'form-control col-sm-7', rows: 5 %>
  </div>
  <div class="text-center">
    <p>※タイトルは20文字以内<br>
       内容は2000字以内
    </p>
  </div>
  
  <div class="text-center">
    <%= f.submit '更新する', class: 'btn btn-light' %>
  </div>
<% end %>
</div>

app/views/articles/hashtag.html.erb
<div class="text-center mt-1">
  <h1>#<%= @hashtag.hashname %>を含む記事一覧</h1>
</div>
<%= render "articles", articles: @articles %>

app/views/articles/index.html.erb
<% if @articles.blank? %>
<p class="text-center">まだ投稿はありません</p>
<% else %>
<div class="text-center mt-1">
  <h1>全ユーザーの記事一覧</h1>
  
  <%= render "search_form" %>

</div>
<%= render "articles", articles: @articles %>
<% end %>

app/views/articles/new.html.erb
<div class="text-center">
  <h1 class="mt-2">記事投稿フォーム</h1>
</div>

<div class="container">
<%= form_with(model: @article, local: true) do |f| %>
  <%= render 'layouts/error_messages', model: f.object %>
  
  <div class="form-group row">
    <div class="col-sm-5 text-center col-form-label">
    <%= f.label :title,'タイトル:' %>
    </div>
    <%= f.text_field :title, class: 'form-control col-sm-7'%>
  </div>

  <div class="form-group row">
    <div class="col-sm-5 text-center col-form-label">
    <%= f.label :content, '内容:' %>
    </div>
    <%= f.text_area :content, class: 'form-control col-sm-7', rows: 5 %>
  </div>
  
  <div class="form-group row">
    <div class="col-sm-5 text-center col-form-label">
    <%= f.label :category_id, 'カテゴリー:' %>
    </div>
    <%= f.collection_select  :category_id, Category.all, :id, :name, include_blank: "選択して下さい" %>
  </div>
  
  <div class="text-center">
    <p>※タイトルは20文字以内<br>
       内容は2000字以内
    </p>
  </div>
  
  <div class="text-center">
  <%= f.submit '投稿する', class: 'btn btn-light' %>
  </div>
<% end %>
</div>

app/views/articles/search.html.erb
<!--<div class="text-center mt-1">-->
<!--  <h1>検索結果</h1>-->
<!--  <p>検索ワード：<%= @search_word %></p>-->
<!--  <p>カテゴリー：<%=  @search_category %></p>-->
<!--  <p><#%= @articles_count %>件</p>-->
  
  <!--<#% if @search_word == "指定なし" %>-->
<!--  <#% @search_word = "" %>-->
<!--  <#% end %>-->
  
<!--  <#%= render "search_form" %>-->
  
<!--</div>-->
<div class="text-center mt-1">
  <h1>検索結果</h1>
  <p>検索ワード：<%= @search_word %></p>
  <% if @category.blank? %>
  <p>カテゴリー：指定なし</p>
  <% else %>
  <p>カテゴリー：<%=  @category.name %></p>
  <% end %>
  <p><%= @articles_count %>件</p>
  
  <% if @search_word == "指定なし" %>
  <% @search_word = "" %>
  <% end %>
  
  <%= render "search_form" %>
  
</div>
  <% if @articles.blank? %>
  <p class="text-center mt-5">条件に当てはまる記事が見つかりませんでした</p>
  <% else %>
  <%= render "articles", articles: @articles %>
  <% end %>

app/views/articles/show.html.erb
<div class="text-center">
  <h1><%= @article.title %></h1>
</div>
<div class="d-flex flex-row justify-content-end">
  <p class="mr-1">投稿者：</p><%= link_to @article.user.name, user_path(@article.user) %>
</div>
<div class="d-flex flex-row justify-content-end">
  <p class="mr-1">カテゴリー：</p><%= link_to @article.category.name, "/articles/category/#{@article.category.id}" %>
</div>
<div class="mx-auto">
  <% content = safe_join(@article.content.split("\n"),tag(:br)) %>
  <%= render_with_hashtags(content) %>
</div>
<% if current_user == @article.user %>
  <div class="justify-content-around mt-2 mb-3 row">
    <div class="col-sm-3 justify-content-center d-flex mb-1">
      <%= link_to "この記事を編集", edit_article_path, class: "btn btn-dark" %>
    </div>
    <div class="col-sm-3 justify-content-center d-flex">
      <%= link_to "この記事を削除", @article, method: :delete, data: { confirm: "本当にこの記事を削除してもいいですか？" }, class: 'btn btn-dark' %>
    </div>
  </div>
<% else %>
  <div class="justify-content-around mt-2 mb-3 row">
    <div class="col-sm-3 justify-content-center d-flex mb-1">
      <%= render "favorites/favorite_button",article: @article %>
    </div>
    <div class="col-sm-3 justify-content-center d-flex">
      <%= render 'relationships/follow_button', user: @user %>
    </div>
  </div>
<% end %>