config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "toppages#index"
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get "signup", to: "users#new"
  resources :users, only: [:index, :show, :new, :create, :edit, :update] do
    member do
      get :followings
      get :followers
      get :likes
    end
    collection do
      get :search
    end
  end
  
  resources :articles do
    collection do
      get :search
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
  
  get '/articles/hashtag/:hashtag_id', to: "articles#hashtag"
  get "/articles/category/:category_id", to: "articles#category"
  
  resources :hashtags, only: [:index]
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { in: 2..10 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  validates :self_introduction, length: { maximum: 50 }
  has_secure_password
  validates :password, presence: true, length: { in: 6..20 }
  
  mount_uploader :image, ImageUploader
  
  has_many :articles
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverses_of_relationship, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverses_of_relationship, source: :user
  has_many :favorites
  has_many :likes, through: :favorites, source: :article
  
  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end
  
  def follow_articles
    #Article.where(user_id: self.following_ids + [self.id])
    Article.where(user_id: self.following_ids)
  end
  
  def favorite(article)
    favorites.find_or_create_by(article_id: article.id)
  end
  
  def unfavorite(article)
    favorite = favorites.find_by(article_id: article.id)
    favorite.destroy if favorite
  end
  
  def favorite?(article)
    self.likes.include?(article)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  skip_before_action :require_user_logged_in, only: [:new, :create]
  before_action :correct_user, only: [:edit, :update]
  before_action :set_user, only: [:show, :edit, :update, :followings, :followers, :likes]
  
  def index
    @users = User.order(id: :desc).page(params[:page]).per(5)
  end
  
  def show
    @articles = @user.articles.order(id: :desc).page(params[:page]).per(4)
    counts(@user)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      session[:user_id] = @user.id
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = 'ユーザー情報を変更しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザー情報の変更に失敗しました。'
      render :edit
    end
  end
  
  def followings
    @followings = @user.followings.page(params[:page]).per(5)
    counts(@user)
  end
  
  def followers
    @followers = @user.followers.page(params[:page]).per(5)
    counts(@user)
  end
  
  def likes
    @likes = @user.likes.page(params[:page]).per(4)
    counts(@user)
  end
  
  def search
    @search_word = params[:search]
    @users = User.where("(name like ?) ","%#{@search_word}%").page(params[:page]).per(5)
    @users_count = User.where("(name like ?) ","%#{@search_word}%").count
    
    if @search_word.blank?
      @search_word = "指定なし"
    end
    
  end
  
  private
  
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :image, :remove_image, :email, :self_introduction, :password, :password_confirmation)
  end
  def correct_user
    @user =  User.find(params[:id])
    unless current_user == @user
      redirect_to root_url
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  end
end

app/views/users/_search_form.html.erb
<%= form_with(url: search_users_path, local: true, method: :get) do |f| %>
  <%= text_field_tag :search,@search_word, placeholder: "検索ワードを入力",size: "30",maxlength: "20" %>
  <%= f.submit 'ユーザーを検索', class: 'btn btn-light' %>
<% end %>

app/views/users/_users.html.erb
<div class="mb-2">
  <% users.each do |user| %>
      <div class="mt-2 border border-dark rounded p-1 mx-auto row justify-content-center">
        <div class=" col-lg-2 p-0 d-flex flex-row justify-content-center">
          <%#ユーザー画像設定用%>
          <%# if user.image.blank? %>
            <img src="/assets/no_image.png" class='hidden rounded rounded-circle border' width="30" height="30" />
          <%# else %>
            <%#= image_tag user.image.to_s, :size => '30', class: "rounded rounded-circle" if user.image? %>
          <%# end %>
          <div class="d-flex align-items-center ml-3 m-l-0 mr-0 justify-content-center"><%= link_to user.name, user_path(user) %></div>
        </div>
        <div class="d-flex align-items-center justify-content-center mt-2 mb-2 col-lg-5">記事数 :<div class="ml-1 mr-1"><%= user.articles.count %></div>/ フォロー :<div class="ml-1 mr-1"><%= user.followings.count %></div>/ フォロワー :<div class="ml-1 mr-1 align-items-center"><%= user.followers.count %></div></div>
          <% if current_user == user %>
          <div class="d-flex align-items-center col-lg-3 m-l-0 mr-0">
            <div class="bg-dark text-white rounded m-0 p-2 mx-auto">あなたです</div>
          </div>
          <% else %>
          <div class="d-flex align-items-center justify-content-center col-lg-3 m-l-0 mr-0">
            <div class="mx-auto"><%= render 'relationships/follow_button', user: user %></div>
          </div>
          <% end %>
        
      </div>
  <% end %>
</div>
<%= paginate users %>

app/views/users/edit.html.erb
<div class="text-center">
  <h1 class="mt-2">ユーザー情報編集ページ</h1>
</div>
<div class="container">

  <%= form_with(model: @user, local: true) do |f| %>
  <%= render 'layouts/error_messages', model: f.object %>
    
    <!--ユーザー画像設定用
    <%# if @user.image.blank? %>
      <div class="form-group row">
      <div class="col-sm-5 text-center col-form-label align-items-center d-flex justify-content-center">
      <%#= f.label :name,'ユーザー画像:' %>
      </div>
      <div class="col-sm-7">
      <div class="d-flex justify-content-center">
        <img id="user_image_prev" src="/assets/no_image.png" class='hidden rounded rounded-circle border' width="100" height="100" /></div>
      <div class="d-flex justify-content-center"><%#= f.file_field :image, id: 'user_img' %></div>
      </div>
      </div>
    <%# else %>
      <div class="form-group row">
      <div class="col-sm-5 text-center col-form-label align-items-center d-flex justify-content-center">
      <%#= f.label :name,'ユーザー画像:' %>
      </div>
      <div class="col-sm-7">
      <div class="d-flex justify-content-center">
        <%#= image_tag @user.image.url, :size => '100', class: "rounded rounded-circle border", id: "user_image_prev" if @user.image? %></div>
      <div class="d-flex justify-content-center"><%#= f.file_field :image, id: 'user_img' %></div>
      <div class="d-flex justify-content-center"><%#= f.check_box :remove_image %>画像をなくす場合はチェックして更新</div>
      </div>
      </div>
    <%# end %>
      <script>
        $( document ).on('turbolinks:load', function() {
          function readURL(input) {
            if (input.files && input.files[0]) {
              var reader = new FileReader();
              reader.onload = function (e) {
                $('#user_image_prev').attr('src', e.target.result);
              }
              reader.readAsDataURL(input.files[0]);
            }
          }
          $("#user_img").change(function(){
            $('#user_image_prev').removeClass('hidden');
            readURL(this);
          });
        });
      </script>
      -->
    
    <div class="form-group row">
      <div class="col-sm-5 text-center col-form-label">
      <%= f.label :name,'ユーザーネーム:' %>
      </div>
      <%= f.text_field :name, class: 'form-control col-sm-7' %>
    </div>

    <div class="form-group row">
      <div class="col-sm-5 text-center col-form-label">
      <%= f.label :email, 'メールアドレス:' %>
      </div>
      <%= f.email_field :email, class: 'form-control col-sm-7' %>
    </div>
    
    <div class="form-group row">
      <div class="col-sm-5 text-center col-form-label">
      <%= f.label :self_introduction, '自己紹介文:' %>
      </div>
      <%= f.text_field :self_introduction, class: 'form-control col-sm-7' %>
    </div>

    <div class="form-group row">
      <div class="col-sm-5 text-center col-form-label">
      <%= f.label :password, 'パスワード:' %>
      </div>
      <%= f.password_field :password, class: 'form-control col-sm-7' %>
    </div>

    <div class="form-group row">
      <div class="col-sm-5 text-center col-form-label">
      <%= f.label :password_confirmation, 'パスワード(確認):' %>
      </div>
      <%= f.password_field :password_confirmation, class: 'form-control col-sm-7' %>
    </div>
    <div class="text-center">
      <p>※ユーザーネームは2~10文字、パスワードは6~20文字<br>自己紹介文は50文字以内で空白でも可</p>
      <%= f.submit '更新する', class: 'btn btn-dark' %>
    </div>
  <% end %>
</div>
  <div>
    <u><%= link_to "＜戻る", user_path(@user), class: "text-dark" %></u>
  </div>

app/views/users/followers.html.erb
<div class="text-center">
  <p><%= link_to @user.name, user_path(@user) %>のフォロー / フォロワー一覧</p>
</div>
<ul class="nav nav-tabs nav-justified mb-3 mt-3">
  <li class="nav-item"><%= link_to "フォロー", followings_user_path(@user), class: "nav-link" %></li>
  <li class="nav-item"><%= link_to "フォロワー", followers_user_path(@user),class: "nav-link active" %></li>
</ul>
<% if @followers.blank? %>
  <p class="text-center">フォローされているユーザーはいません</p>
<% else %>
  <%= render 'users', users: @followers %>
<% end %>

app/views/users/followings.html.erb
<div class="text-center">
  <p><%= link_to @user.name, user_path(@user) %>のフォロー / フォロワー一覧</p>
</div>
<ul class="nav nav-tabs nav-justified mb-3 mt-3">
  <li class="nav-item"><%= link_to "フォロー", followings_user_path(@user), class: "nav-link active" %></li>
  <li class="nav-item"><%= link_to "フォロワー", followers_user_path(@user),class: "nav-link" %></li>
</ul>
<% if @followings.blank? %>
  <p class="text-center">フォローしているユーザーはいません</p>
<% else %>
  <%= render 'users', users: @followings %>
<% end %>

app/views/users/index.html.erb
<div class="text-center">
  <h1>登録ユーザー一覧</h1>
  
  <%= render "search_form" %>
  
</div>
<%= render "users", users: @users %>

app/views/users/likes.html.erb
<div class="text-center">
  <p><%= link_to @user.name, user_path(@user) %>のお気に入り一覧</p>
</div>
 <% if @likes.blank? %>
  <p class="text-center">お気に入りしている投稿はありません</p>
<% else %>
  <%= render 'articles/articles', articles: @likes %>
<% end %>

app/views/users/new.html.erb
<div class="text-center">
  <h1 class="mt-2">新規登録</h1>
</div>

<div class="container">

    <%= form_with(model: @user, local: true) do |f| %>
    <%= render 'layouts/error_messages', model: f.object %>
      
      <!--ユーザー画像設定用
      <div class="form-group row">
      <div class="col-sm-5 text-center col-form-label align-items-center d-flex justify-content-center">
      <%#= f.label :name,'ユーザー画像:' %>
      </div>
      <div class="col-sm-7">
      <div class="d-flex justify-content-center"><img id="user_image_prev" src="/assets/no_image.png" class='hidden rounded rounded-circle border' width="100" height="100" /></div>
      <div class="d-flex justify-content-center"><%#= f.file_field :image, id: 'user_img' %></div>
      </div>
      </div>
      <script>
        $( document ).on('turbolinks:load', function() {
          function readURL(input) {
            if (input.files && input.files[0]) {
              var reader = new FileReader();
              reader.onload = function (e) {
                $('#user_image_prev').attr('src', e.target.result);
              }
              reader.readAsDataURL(input.files[0]);
            }
          }
          $("#user_img").change(function(){
            $('#user_image_prev').removeClass('hidden');
            readURL(this);
          });
        });
      </script>
      -->
      
      <div class="form-group row">
        <div class="col-sm-5 text-center col-form-label">
        <%= f.label :name,'ユーザーネーム:' %>
        </div>
        <%= f.text_field :name, class: 'form-control col-sm-7' %>
      </div>

      <div class="form-group row">
        <div class="col-sm-5 text-center col-form-label">
        <%= f.label :email, 'メールアドレス:' %>
        </div>
        <%= f.email_field :email, class: 'form-control col-sm-7' %>
      </div>
      
      <div class="form-group row">
        <div class="col-sm-5 text-center col-form-label">
        <%= f.label :self_introduction, '自己紹介文:' %>
        </div>
        <%= f.text_field :self_introduction, class: 'form-control col-sm-7' %>
      </div>

      <div class="form-group row">
        <div class="col-sm-5 text-center col-form-label">
        <%= f.label :password, 'パスワード:' %>
        </div>
        <%= f.password_field :password, class: 'form-control col-sm-7' %>
      </div>

      <div class="form-group row">
        <div class="col-sm-5 text-center col-form-label">
        <%= f.label :password_confirmation, 'パスワード(確認):' %>
        </div>
        <%= f.password_field :password_confirmation, class: 'form-control col-sm-7' %>
      </div>
      <div class="text-center">
        <p>※ユーザーネームは2~10文字、パスワードは6~20文字<br>自己紹介文は50文字以内で空白でも可</p>
        <%= f.submit '登録する', class: 'btn btn-dark' %>
      </div>
    <% end %>
    <div class="row mt-2">
      <div class="d-flex flex-row mx-auto">
        <p>既に登録している方はコチラから<%= link_to 'ログイン', login_path %>
      </div>
    </div>
</div>
  <div>
    <u><a href="/" class="text-dark">＜戻る</a></u>
  </div>

app/views/users/search.html.erb
<div class="text-center mt-1">
  <h1>検索結果</h1>
  <p>検索ワード：<%= @search_word %></p>
  <p><%= @users_count %>件</p>
  
  <% if @search_word == "指定なし" %>
  <% @search_word = "" %>
  <% end %>
  
  <%= render "search_form" %>
  
</div>
  <% if @users.blank? %>
  <p class="text-center mt-5">ユーザーが見つかりませんでした</p>
  <% else %>
  <%= render 'users', users: @users %>
  <% end %>

app/views/users/show.html.erb
<div class="text-center">
  <h1><%= @user.name %></h1>
</div>
<div class="d-flex flex-row justify-content-around align-items-center">
<div>
  <%#ユーザー画像設定用%>
  <%# if @user.image.blank? %>
    <img src="/assets/no_image.png" class='hidden rounded rounded-circle border' width="200" height="200" />
  <%# else %>
    <%#= image_tag @user.image.to_s, :size => '200', class: "rounded rounded-circle" if @user.image? %>
  <%# end %>
</div>
<div>
  <% if @user.self_introduction.blank? %>
    <p>自己紹介文が設定されていません</p>
  <% else %>
    <%= @user.self_introduction %>
  <% end %>
</div>
</div>
<% if current_user == @user %>
<div class="text-center">
  <%= link_to "ユーザー情報を編集する", edit_user_path %>
</div>
<% end %>
<div class="text-center">
  <p>フォロー :<%= link_to @count_followings, followings_user_path(@user), class: "ml-1 mr-1" %>/ フォロワー :<%= link_to @count_followers, followers_user_path(@user), class: "ml-1 mr-1" %>/ お気に入り :<%= link_to @count_likes, likes_user_path(@user), class: "ml-1 mr-1" %></p>
</div>
<div class="text-center">
<%= render 'relationships/follow_button', user: @user %>
</div>
<div class="mt-2">
  <p>投稿した記事</p>
</div>
<% if @user.articles.blank? %>
  <p class="text-center">まだ投稿がありません</p>
<% else %>
  <div>
    <%= render "articles/articles", articles: @articles %>
  </div>
<% end %>