config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "toppages#index"
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get "signup", to: "users#new"
  resources :users, only: [:index, :show, :new, :create, :edit, :update] do
    member do
      get :followings
      get :followers
      get :likes
    end
    collection do
      get :search
    end
  end
  
  resources :articles do
    collection do
      get :search
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
  
  get '/articles/hashtag/:hashtag_id', to: "articles#hashtag"
  get "/articles/category/:category_id", to: "articles#category"
  
  resources :hashtags, only: [:index]
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header>
<% if logged_in? %>
  <nav class="navbar navbar-expand navbar-dark bg-dark">
      <a href="/" class="navbar-brand mr-auto">Skill Share</a>
      <div class="nav-item dropdown">
        <a href="#" class="nav-link dropdown-toggle navbar-brand m-0" data-toggle="dropdown">Menu</a>
        <div class="dropdown-menu dropdown-menu-right">
          <%= link_to 'マイプロフィール', user_path(current_user), class: "dropdown-item" %>
          <%= link_to '記事一覧', articles_path, class: "dropdown-item" %>
          <%= link_to '記事投稿', new_article_path, class: "dropdown-item" %>
          <%= link_to 'ハッシュタグ一覧', hashtags_path, class: "dropdown-item" %>
          <%= link_to 'ユーザー一覧', users_path, class: "dropdown-item" %>
          <%= link_to 'ログアウト', logout_path, method: :delete, class: "dropdown-item" %>
        </div>
      </div>
  </nav>
<% else %>
  <nav class="navbar navbar-expand navbar-dark bg-dark">
    <div class="navbar-collapse justify-content-center">
      <a href="/" class="navbar-brand nav-link">Skill Share</a>
    </div>
  </nav>
<% end %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html  lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Skill Share</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">
    
    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </head>

  <body>
    
    <%= render 'layouts/navbar' %>
    
    <div class="container">
    
      <%= render 'layouts/flash_messages' %>

      <%= yield %>

    </div>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </body>
</html>